#!/bin/bash
ireal=$1
nthread=8
amp=5e-14

. ./settings

rm -rf real.$ireal
mkdir real.$ireal
cd real.$ireal
cp ../*.par .
ln -s ../*.ideal .
ln -s ../*.add* .

echo -ne "REAL $ireal\r"
for i in *.par ; do
   while [[ `jobs -r | wc -l` -ge $nthread ]] ; do
	  n=`jobs -r | wc -l`
	  echo -ne "Wait ($n/$nthread) running" `date +%T` `cat /proc/loadavg` "    \r"
	  sleep 0.05
   done

   psr=`basename $i .par`
   nobs=`wc -l $psr.ideal | awk '{print $1+1000}'`
   echo -ne "$ireal $psr \r"
   red=""
   if [[ -e $psr.ideal.addRedNoise ]] ; then
	  red="-corn $psr.ideal.addRedNoise $ireal"
   fi
   echo tempo2-mjk -gr createRealisation -f $psr.ideal -corn $psr.ideal.addGauss $ireal -corn $psr.ideal.addGWB $ireal $red -npsr 1 -nobs $nobs
   tempo2-mjk -gr createRealisation -f $psr.ideal -corn $psr.ideal.addGauss $ireal -corn $psr.ideal.addGWB $ireal $red -npsr 1 -nobs $nobs  > /dev/null && mv $psr.ideal.real $psr.tim &
   echo -n "-f $psr.par $psr.tim " >> many
done

wait


if [[ -e ../tempo2.model ]] ;then
   cp ../*.model .
else

   for i in *.par ; do
	  psr=`basename $i .par`
	  rms=`/u/kei041/bin/get_wrms.py $psr.tim`
	  nobs=`wc -l $psr.tim | awk '{print $1+1000}'`
	  tempo2-mjk -gr analyticChol -gwamp $amp -f $psr.par $psr.tim -rms $rms -npsr 1 -nobs $nobs > /dev/null &
   done

   echo "wait for analyticChol"
   wait

   echo "MODEL T2" > tempo2.model
   for i in J*.model ; do
	  psr=`basename $i .model`
	  echo "PSR $psr" >> tempo2.model
	  echo "INCLUDE $i" >> tempo2.model
	  if grep -q $psr ../psr.noise ; then
		 set -- `grep $psr ../psr.noise`
		 if [[ $3 != '0' ]] ; then
			echo "MODEL T2PowerLaw $4 $3 $5" >> tempo2.model
		 fi
	  fi
   done
   cp *.model ..
fi

