#!/bin/bash
wd=`pwd`
root=`dirname $0`
. ./settings

for trial in `seq 0 $(($nreal-1))` ; do
   $root/make_1real $trial
   if [[ ! -e real.$trial ]] ; then
	  echo "ERROR NO real.$trial"
	  exit
   fi
done


